---
title: "Matching Estimators in R"
author: "Shenyang Guo and Peter Sun"
date: "September, 2021"
output: word_document
---

# Load Packages

```{r message=F, warning=F, error=F}
library(haven)
library(lmtest)
library(tidyverse)
library(broom)
library(Matching)
library(tidyr)
library(flextable)
select <- dplyr::select
```

# Load Data

```{r}
d <- read_dta("data/cds_pcss97.dta") %>%
  haven::zap_formats() %>%
  sjlabelled::remove_all_labels() %>%
  as_tibble()
```

# Breusch-Pagan Test for Heteroskedasticity

```{r message=FALSE, warning=FALSE}
m0 <- lm(pcss97 ~ kuse + male + black + age97 + pcged97 + mratio96 + pcg_adc, data = d)
get_bptest <- function(data, lm.model, var) {
  b <- lmtest::bptest(lm.model, as.formula(paste0("~", var)), 
                      data = data, studentize = F)
  return(tibble(variable = var, statistic = b$statistic, 
                df = b$parameter, p.value = b$p.value))
}
map_dfr(c("kuse", "male", "black", "age97", "pcged97", "mratio96", "pcg_adc"), 
        get_bptest, data = d, lm.model = m0) %>%
  flextable() %>%
  flextable::set_table_properties(width = 1, layout = "autofit")
```

# Matching Estimators

## Define Outcome (Y), Treatment Index (Tr), and Variables to Match On (X)

```{r}
Y <- d$pcss97
Tr <- d$kuse
X <- select(d, male, black, age97, pcged97, mratio96, pcg_adc)
```

## Get Estimators Individually

```{r eval=F}
# Sample Average Treatment Effect (SATE)
summary(Match(Y = Y, Tr = Tr, X = X, M = 4, BiasAdjust = T, Var.calc = 4,
              estimand = "ATE", sample = T))

# Population Average Treatment Effect (PATE)
summary(Match(Y = Y, Tr = Tr, X = X, M = 4, BiasAdjust = T, Var.calc = 4,
              estimand = "ATE", sample = F))

# Sample average treatment effect for the treated (SATT)
summary(Match(Y = Y, Tr = Tr, X = X, M = 4, BiasAdjust = T, Var.calc = 4,
              estimand = "ATT", sample = T))

# Population average treatment effect for the treated (PATT)
summary(Match(Y = Y, Tr = Tr, X = X, M = 4, BiasAdjust = T, Var.calc = 4,
              estimand = "ATT", sample = F))

# Sample average treatment effect for the controls (SATC)
summary(Match(Y = Y, Tr = Tr, X = X, M = 4, BiasAdjust = T, Var.calc = 4,
              estimand = "ATC", sample = T))

# Population average treatment effect for the controls (PATC)
summary(Match(Y = Y, Tr = Tr, X = X, M = 4, BiasAdjust = T, Var.calc = 4,
              estimand = "ATC", sample = F))
```

## Get All Estimators

```{r}
get_match <- function(estimand, sample) {
  m <- Match(Y = Y, Tr = Tr, X = X, M = 4, BiasAdjust = TRUE, Var.calc = 4,
              estimand = estimand, sample = sample)
  return(list(
    est = m$est[,1],
    se = m$se,
    t.stat = m$est[,1]/m$se,
    p = (1 - pnorm(abs(m$est[,1]/m$se))) * 2
  ))
}
tribble(
  ~estimator, ~estimand, ~sample,
  "SATE", "ATE", T,
  "PATE", "ATE", F,
  "SATT", "ATT", T,
  "PATT", "ATT", F,
  "SATC", "ATC", T,
  "PATC", "ATC", F
) %>%
  rowwise() %>%
  mutate(match = list(get_match(estimand, sample))) %>%
  tidyr::unnest_wider(match) %>%
  select(-estimand, -sample) %>%
  flextable::flextable() %>%
  flextable::set_table_properties(width = 1, layout = "autofit")
```
